# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Doconvo < Formula
  desc "Document conversation assistant with RAG capabilities"
  homepage "https://github.com/MegaGrindStone/doconvo"
  version "0.2.0"

  on_macos do
    on_intel do
      url "https://github.com/MegaGrindStone/doconvo/releases/download/v0.2.0/doconvo_Darwin_x86_64.tar.gz"
      sha256 "b544f81230a68ead76c32b14633a034c4342bb6a74973fff40cd3dd97d58fc25"

      def install
        bin.install "doconvo"
      end
    end
    on_arm do
      url "https://github.com/MegaGrindStone/doconvo/releases/download/v0.2.0/doconvo_Darwin_arm64.tar.gz"
      sha256 "df87f25337198f20f3e6c155192ea07b8cb3f2f7b02a701ca59dd690b14ac778"

      def install
        bin.install "doconvo"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/MegaGrindStone/doconvo/releases/download/v0.2.0/doconvo_Linux_x86_64.tar.gz"
        sha256 "307496a1f7bccc1b67937bdd36a93cb30b782473b79856fff8e57c244faf7d7f"

        def install
          bin.install "doconvo"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/MegaGrindStone/doconvo/releases/download/v0.2.0/doconvo_Linux_arm64.tar.gz"
        sha256 "c5790f233328760336d630474fb818fd84e1e29c643d4fe398f641b46ebae656"

        def install
          bin.install "doconvo"
        end
      end
    end
  end
end
